//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NethereumUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int FileId { get; set; }
        public string FileName { get; set; }
        public string Size { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string UploadedBy { get; set; }
    }
}
